#!/usr/bin/env python3
#
# Copyright (C) 2020 Norimitsu Sugimoto
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

"""
emoji-sequences.txt
    self.cldr_short_name, japanese kana, japanese word type
"""
EMOJI_KANA_TRANS_TABLE = [
    # Basic_Emoji
    ("watch", "#T35", "とけい"),
    ("fast-forward button", "#T35", "やじるし"),
    ("alarm clock", "#T35", "めざまし"),
    ("hourglass not done", "#T35", ""),
    ("white medium-small square", "#T35", ""),
    ("umbrella with rain drops", "#T35", ""),
    ("Aries", "#T35", ""),
    ("wheelchair symbol", "#T35", ""),
    ("anchor", "#T35", ""),
    ("high voltage", "#T35", ""),
    ("white circle", "#T35", ""),
    ("soccer ball", "#T35", ""),
    ("snowman without snow", "#T35", ""),
    ("Ophiuchus", "#T35", ""),
    ("no entry", "#T35", ""),
    ("church", "#T35", ""),
    ("fountain", "#T35", ""),
    ("sailboat", "#T35", ""),
    ("tent", "#T35", ""),
    ("fuel pump", "#T35", ""),
    ("check mark button", "#T35", ""),
    ("raised fist", "#T35", ""),
    ("sparkles", "#T35", ""),
    ("cross mark", "#T35", ""),
    ("cross mark button", "#T35", ""),
    ("question mark", "#T35", ""),
    ("exclamation mark", "#T35", ""),
    ("plus", "#T35", ""),
    ("curly loop", "#T35", ""),
    ("double curly loop", "#T35", ""),
    ("black large square", "#T35", ""),
    ("star", "#T35", ""),
    ("hollow red circle", "#T35", ""),
    ("mahjong red dragon", "#T35", "ちゅん"),
    ("joker", "#T35", ""),
    ("AB button (blood type)", "#T35", ""),
    ("CL button", "#T35", ""),
    ("Japanese “here” button", "#T35", ""),
    ("Japanese “free of charge” button", "#T35", ""),
    ("Japanese “reserved” button", "#T35", ""),
    ("Japanese “prohibited” button", "#T35", ""),
    ("Japanese “application” button", "#T35", ""),
    ("Japanese “bargain” button", "#T35", ""),
    ("cyclone", "#T35", ""),
    ("globe showing Europe-Africa", "#T35", ""),
    ("globe showing Asia-Australia", "#T35", ""),
    ("globe with meridians", "#T35", ""),
    ("new moon", "#T35", ""),
    ("waxing crescent moon", "#T35", ""),
    ("first quarter moon", "#T35", ""),
    ("waning gibbous moon", "#T35", ""),
    ("crescent moon", "#T35", ""),
    ("new moon face", "#T35", ""),
    ("first quarter moon face", "#T35", ""),
    ("last quarter moon face", "#T35", ""),
    ("full moon face", "#T35", ""),
    ("glowing star", "#T35", ""),
    ("hot dog", "#T35", ""),
    ("chestnut", "#T35", ""),
    ("evergreen tree", "#T35", ""),
    ("palm tree", "#T35", ""),
    ("tulip", "#T35", ""),
    ("lemon", "#T35", ""),
    ("banana", "#T35", ""),
    ("pear", "#T35", ""),
    ("peach", "#T35", ""),
    ("baby bottle", "#T35", ""),
    ("bottle with popping cork", "#T35", ""),
    ("ribbon", "#T35", ""),
    ("carousel horse", "#T35", ""),
    ("sports medal", "#T35", ""),
    ("trophy", "#T35", ""),
    ("horse racing", "#T35", ""),
    ("american football", "#T35", ""),
    ("rugby football", "#T35", ""),
    ("person swimming", "#T35", ""),
    ("cricket game", "#T35", ""),
    ("house", "#T35", ""),
    ("post office", "#T35", ""),
    ("hospital", "#T35", ""),
    ("black flag", "#T35", ""),
    ("badminton", "#T35", ""),
    ("cat", "#T35", ""),
    ("dragon", "#T35", ""),
    ("snail", "#T35", ""),
    ("ram", "#T35", ""),
    ("ewe", "#T35", ""),
    ("rooster", "#T35", ""),
    ("chicken", "#T35", ""),
    ("dog", "#T35", ""),
    ("pig", "#T35", ""),
    ("boar", "#T35", ""),
    ("camel", "#T35", ""),
    ("two-hump camel", "#T35", ""),
    ("eyes", "#T35", ""),
    ("ear", "#T35", ""),
    ("busts in silhouette", "#T35", ""),
    ("boy", "#T35", ""),
    ("men holding hands", "#T35", ""),
    ("police officer", "#T35", ""),
    ("thought balloon", "#T35", ""),
    ("white flower", "#T35", ""),
    ("euro banknote", "#T35", ""),
    ("money with wings", "#T35", ""),
    ("open mailbox with raised flag", "#T35", ""),
    ("postbox", "#T35", ""),
    ("postal horn", "#T35", ""),
    ("newspaper", "#T35", ""),
    ("no mobile phones", "#T35", ""),
    ("antenna bars", "#T35", ""),
    ("camera with flash", "#T35", ""),
    ("video camera", "#T35", ""),
    ("prayer beads", "#T35", ""),
    ("clockwise vertical arrows", "#T35", ""),
    ("counterclockwise arrows button", "#T35", ""),
    ("speaker low volume", "#T35", ""),
    ("speaker medium volume", "#T35", ""),
    ("speaker high volume", "#T35", ""),
    ("bell with slash", "#T35", ""),
    ("bookmark", "#T35", ""),
    ("microscope", "#T35", ""),
    ("crystal ball", "#T35", ""),
    ("kaaba", "#T35", ""),
    ("one o’clock", "#T35", ""),
    ("one-thirty", "#T35", ""),
    ("man dancing", "#T35", ""),
    ("middle finger", "#T35", ""),
    ("black heart", "#T35", ""),
    ("mount fuji", "#T35", ""),
    ("grinning face", "#T35", ""),
    ("beaming face with smiling eyes", "#T35", ""),
    ("smiling face with halo", "#T35", ""),
    ("winking face", "#T35", ""),
    ("smiling face with sunglasses", "#T35", ""),
    ("smirking face", "#T35", ""),
    ("neutral face", "#T35", ""),
    ("expressionless face", "#T35", ""),
    ("unamused face", "#T35", ""),
    ("confused face", "#T35", ""),
    ("confounded face", "#T35", ""),
    ("kissing face", "#T35", ""),
    ("face blowing a kiss", "#T35", ""),
    ("kissing face with smiling eyes", "#T35", ""),
    ("kissing face with closed eyes", "#T35", ""),
    ("face with tongue", "#T35", ""),
    ("winking face with tongue", "#T35", ""),
    ("worried face", "#T35", ""),
    ("angry face", "#T35", ""),
    ("frowning face with open mouth", "#T35", ""),
    ("fearful face", "#T35", ""),
    ("grimacing face", "#T35", ""),
    ("loudly crying face", "#T35", ""),
    ("face with open mouth", "#T35", ""),
    ("anxious face with sweat", "#T35", ""),
    ("sleeping face", "#T35", ""),
    ("dizzy face", "#T35", ""),
    ("face without mouth", "#T35", ""),
    ("face with medical mask", "#T35", ""),
    ("slightly frowning face", "#T35", ""),
    ("person gesturing NO", "#T35", ""),
    ("rocket", "#T35", ""),
    ("helicopter", "#T35", ""),
    ("railway car", "#T35", ""),
    ("train", "#T35", ""),
    ("metro", "#T35", ""),
    ("light rail", "#T35", ""),
    ("station", "#T35", ""),
    ("tram", "#T35", ""),
    ("bus", "#T35", ""),
    ("oncoming bus", "#T35", ""),
    ("trolleybus", "#T35", ""),
    ("bus stop", "#T35", ""),
    ("minibus", "#T35", ""),
    ("ambulance", "#T35", ""),
    ("oncoming police car", "#T35", ""),
    ("taxi", "#T35", ""),
    ("oncoming taxi", "#T35", ""),
    ("automobile", "#T35", ""),
    ("oncoming automobile", "#T35", ""),
    ("sport utility vehicle", "#T35", ""),
    ("articulated lorry", "#T35", ""),
    ("ship", "#T35", ""),
    ("person rowing boat", "#T35", ""),
    ("speedboat", "#T35", ""),
    ("vertical traffic light", "#T35", ""),
    ("construction", "#T35", ""),
    ("litter in bin sign", "#T35", ""),
    ("bicycle", "#T35", ""),
    ("no bicycles", "#T35", ""),
    ("person walking", "#T35", ""),
    ("no pedestrians", "#T35", ""),
    ("men’s room", "#T35", ""),
    ("shower", "#T35", ""),
    ("person taking bath", "#T35", ""),
    ("bathtub", "#T35", ""),
    ("person in bed", "#T35", ""),
    ("place of worship", "#T35", ""),
    ("stop sign", "#T35", ""),
    ("hindu temple", "#T35", ""),
    ("hut", "#T35", ""),
    ("airplane departure", "#T35", ""),
    ("kick scooter", "#T35", ""),
    ("sled", "#T35", ""),
    ("skateboard", "#T35", ""),
    ("auto rickshaw", "#T35", ""),
    ("pickup truck", "#T35", ""),
    ("orange circle", "#T35", ""),
    ("pinched fingers", "#T35", ""),
    ("white heart", "#T35", ""),
    ("zipper-mouth face", "#T35", ""),
    ("call me hand", "#T35", ""),
    ("love-you gesture", "#T35", ""),
    ("cowboy hat face", "#T35", ""),
    ("face with raised eyebrow", "#T35", ""),
    ("pregnant woman", "#T35", ""),
    ("breast-feeding", "#T35", ""),
    ("selfie", "#T35", ""),
    ("people wrestling", "#T35", ""),
    ("diving mask", "#T35", ""),
    ("wilted flower", "#T35", ""),
    ("1st place medal", "#T35", ""),
    ("curling stone", "#T35", ""),
    ("lacrosse", "#T35", ""),
    ("croissant", "#T35", ""),
    ("dumpling", "#T35", ""),
    ("leafy green", "#T35", ""),
    ("yawning face", "#T35", ""),
    ("smiling face with tear", "#T35", ""),
    ("partying face", "#T35", ""),
    ("ninja", "#T35", ""),
    ("pleading face", "#T35", ""),
    ("sari", "#T35", ""),
    ("lab coat", "#T35", ""),
    ("crab", "#T35", ""),
    ("eagle", "#T35", ""),
    ("giraffe", "#T35", ""),
    ("kangaroo", "#T35", ""),
    ("mammoth", "#T35", ""),
    ("sloth", "#T35", ""),
    ("beaver", "#T35", ""),
    ("guide dog", "#T35", ""),
    ("red hair", "#T35", ""),
    ("safety vest", "#T35", ""),
    ("cheese wedge", "#T35", ""),
    ("cupcake", "#T35", ""),
    ("beverage box", "#T35", ""),
    ("bubble tea", "#T35", ""),
    ("person standing", "#T35", ""),
    ("face with monocle", "#T35", ""),
    ("red envelope", "#T35", ""),
    ("ballet shoes", "#T35", ""),
    ("thong sandal", "#T35", ""),
    ("drop of blood", "#T35", ""),
    ("yo-yo", "#T35", ""),
    ("boomerang", "#T35", ""),
    ("ringed planet", "#T35", ""),
    ("military helmet", "#T35", ""),
    ("fly", "#T35", ""),
    ("anatomical heart", "#T35", ""),
    ("blueberries", "#T35", ""),
    ("copyright", "#T35", ""),
    ("registered", "#T35", ""),
    ("double exclamation mark", "#T35", ""),
    ("exclamation question mark", "#T35", ""),
    ("trade mark", "#T35", ""),
    ("information", "#T35", ""),
    ("left-right arrow", "#T35", ""),
    ("up-down arrow", "#T35", ""),
    ("up-left arrow", "#T35", ""),
    ("up-right arrow", "#T35", ""),
    ("down-right arrow", "#T35", ""),
    ("down-left arrow", "#T35", ""),
    ("right arrow curving left", "#T35", ""),
    ("left arrow curving right", "#T35", ""),
    ("keyboard", "#T35", ""),
    ("eject button", "#T35", ""),
    ("next track button", "#T35", ""),
    ("last track button", "#T35", ""),
    ("play or pause button", "#T35", ""),
    ("stopwatch", "#T35", ""),
    ("timer clock", "#T35", ""),
    ("pause button", "#T35", ""),
    ("stop button", "#T35", ""),
    ("record button", "#T35", ""),
    ("circled M", "#T35", ""),
    ("black small square", "#T35", ""),
    ("white small square", "#T35", ""),
    ("play button", "#T35", ""),
    ("reverse button", "#T35", ""),
    ("white medium square", "#T35", ""),
    ("black medium square", "#T35", ""),
    ("sun", "#T35", ""),
    ("cloud", "#T35", ""),
    ("umbrella", "#T35", ""),
    ("snowman", "#T35", ""),
    ("comet", "#T35", ""),
    ("telephone", "#T35", ""),
    ("check box with check", "#T35", ""),
    ("shamrock", "#T35", ""),
    ("index pointing up", "#T35", ""),
    ("skull and crossbones", "#T35", ""),
    ("radioactive", "#T35", ""),
    ("biohazard", "#T35", ""),
    ("orthodox cross", "#T35", ""),
    ("star and crescent", "#T35", ""),
    ("peace symbol", "#T35", ""),
    ("yin yang", "#T35", ""),
    ("wheel of dharma", "#T35", ""),
    ("frowning face", "#T35", ""),
    ("smiling face", "#T35", ""),
    ("female sign", "#T35", ""),
    ("male sign", "#T35", ""),
    ("chess pawn", "#T35", ""),
    ("spade suit", "#T35", ""),
    ("club suit", "#T35", ""),
    ("heart suit", "#T35", ""),
    ("diamond suit", "#T35", ""),
    ("hot springs", "#T35", ""),
    ("recycling symbol", "#T35", ""),
    ("infinity", "#T35", ""),
    ("hammer and pick", "#T35", ""),
    ("crossed swords", "#T35", ""),
    ("medical symbol", "#T35", ""),
    ("balance scale", "#T35", ""),
    ("alembic", "#T35", ""),
    ("gear", "#T35", ""),
    ("atom symbol", "#T35", ""),
    ("fleur-de-lis", "#T35", ""),
    ("warning", "#T35", ""),
    ("transgender symbol", "#T35", ""),
    ("coffin", "#T35", ""),
    ("funeral urn", "#T35", ""),
    ("cloud with lightning and rain", "#T35", ""),
    ("pick", "#T35", ""),
    ("rescue worker’s helmet", "#T35", ""),
    ("chains", "#T35", ""),
    ("shinto shrine", "#T35", ""),
    ("mountain", "#T35", ""),
    ("umbrella on ground", "#T35", ""),
    ("ferry", "#T35", ""),
    ("skier", "#T35", ""),
    ("ice skate", "#T35", ""),
    ("person bouncing ball", "#T35", ""),
    ("scissors", "#T35", ""),
    ("airplane", "#T35", ""),
    ("envelope", "#T35", ""),
    ("victory hand", "#T35", ""),
    ("writing hand", "#T35", ""),
    ("pencil", "#T35", ""),
    ("black nib", "#T35", ""),
    ("check mark", "#T35", ""),
    ("multiply", "#T35", ""),
    ("latin cross", "#T35", ""),
    ("star of David", "#T35", ""),
    ("eight-spoked asterisk", "#T35", ""),
    ("eight-pointed star", "#T35", ""),
    ("snowflake", "#T35", ""),
    ("sparkle", "#T35", ""),
    ("heart exclamation", "#T35", ""),
    ("red heart", "#T35", ""),
    ("right arrow", "#T35", ""),
    ("right arrow curving up", "#T35", ""),
    ("right arrow curving down", "#T35", ""),
    ("left arrow", "#T35", ""),
    ("up arrow", "#T35", ""),
    ("down arrow", "#T35", ""),
    ("wavy dash", "#T35", ""),
    ("part alternation mark", "#T35", ""),
    ("Japanese “congratulations” button", "#T35", ""),
    ("Japanese “secret” button", "#T35", ""),
    ("A button (blood type)", "#T35", ""),
    ("B button (blood type)", "#T35", ""),
    ("O button (blood type)", "#T35", ""),
    ("P button", "#T35", ""),
    ("Japanese “service charge” button", "#T35", ""),
    ("Japanese “monthly amount” button", "#T35", ""),
    ("thermometer", "#T35", ""),
    ("sun behind small cloud", "#T35", ""),
    ("sun behind large cloud", "#T35", ""),
    ("sun behind rain cloud", "#T35", ""),
    ("cloud with rain", "#T35", ""),
    ("cloud with snow", "#T35", ""),
    ("cloud with lightning", "#T35", ""),
    ("tornado", "#T35", ""),
    ("fog", "#T35", ""),
    ("wind face", "#T35", ""),
    ("hot pepper", "#T35", ""),
    ("fork and knife with plate", "#T35", ""),
    ("military medal", "#T35", ""),
    ("reminder ribbon", "#T35", ""),
    ("studio microphone", "#T35", ""),
    ("level slider", "#T35", ""),
    ("control knobs", "#T35", ""),
    ("film frames", "#T35", ""),
    ("admission tickets", "#T35", ""),
    ("person lifting weights", "#T35", ""),
    ("person golfing", "#T35", ""),
    ("motorcycle", "#T35", ""),
    ("racing car", "#T35", ""),
    ("snow-capped mountain", "#T35", ""),
    ("camping", "#T35", ""),
    ("beach with umbrella", "#T35", ""),
    ("building construction", "#T35", ""),
    ("houses", "#T35", ""),
    ("cityscape", "#T35", ""),
    ("derelict house", "#T35", ""),
    ("classical building", "#T35", ""),
    ("desert", "#T35", ""),
    ("desert island", "#T35", ""),
    ("national park", "#T35", ""),
    ("stadium", "#T35", ""),
    ("white flag", "#T35", ""),
    ("rosette", "#T35", ""),
    ("label", "#T35", ""),
    ("chipmunk", "#T35", ""),
    ("eye", "#T35", ""),
    ("film projector", "#T35", ""),
    ("om", "#T35", ""),
    ("dove", "#T35", ""),
    ("candle", "#T35", ""),
    ("mantelpiece clock", "#T35", ""),
    ("hole", "#T35", ""),
    ("person in suit levitating", "#T35", ""),
    ("detective", "#T35", ""),
    ("sunglasses", "#T35", ""),
    ("spider", "#T35", ""),
    ("spider web", "#T35", ""),
    ("joystick", "#T35", ""),
    ("linked paperclips", "#T35", ""),
    ("pen", "#T35", ""),
    ("fountain pen", "#T35", ""),
    ("paintbrush", "#T35", ""),
    ("crayon", "#T35", ""),
    ("hand with fingers splayed", "#T35", ""),
    ("desktop computer", "#T35", ""),
    ("printer", "#T35", ""),
    ("computer mouse", "#T35", ""),
    ("trackball", "#T35", ""),
    ("framed picture", "#T35", ""),
    ("card index dividers", "#T35", ""),
    ("card file box", "#T35", ""),
    ("file cabinet", "#T35", ""),
    ("wastebasket", "#T35", ""),
    ("spiral notepad", "#T35", ""),
    ("spiral calendar", "#T35", ""),
    ("clamp", "#T35", ""),
    ("old key", "#T35", ""),
    ("rolled-up newspaper", "#T35", ""),
    ("dagger", "#T35", ""),
    ("speaking head", "#T35", ""),
    ("left speech bubble", "#T35", ""),
    ("right anger bubble", "#T35", ""),
    ("ballot box with ballot", "#T35", ""),
    ("world map", "#T35", ""),
    ("couch and lamp", "#T35", ""),
    ("shopping bags", "#T35", ""),
    ("bellhop bell", "#T35", ""),
    ("bed", "#T35", ""),
    ("hammer and wrench", "#T35", ""),
    ("shield", "#T35", ""),
    ("oil drum", "#T35", ""),
    ("motorway", "#T35", ""),
    ("railway track", "#T35", ""),
    ("motor boat", "#T35", ""),
    ("small airplane", "#T35", ""),
    ("satellite", "#T35", ""),
    ("passenger ship", "#T35", ""),
]

if '__main__' == __name__:
    pass
